import type { Metadata } from "next";
import { Geist, Geist_Mono, Libre_Baskerville, Inter, Figtree } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import { cn } from "@/lib/utils";

// Configure Figtree (Sans-Serif for Body text)
const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure Libre Baskerville (Serif for Headings)
const libreBaskerville = Libre_Baskerville({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-baskerville',
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, libreBaskerville.variable, inter.variable, figtree.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
